#!/bin/bash

set -e

psql -U postgres -d webeducation <<'SQL'
GRANT CONNECT ON DATABASE webeducation TO artmxvdb;

GRANT USAGE, CREATE ON SCHEMA public TO artmxvdb;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public TO artmxvdb;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO artmxvdb;

GRANT REFERENCES ON TABLE "Users" TO artmxvdb;
GRANT REFERENCES ON TABLE "Rooms" TO artmxvdb;
GRANT REFERENCES ON TABLE "Messages" TO artmxvdb;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO artmxvdb;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO artmxvdb;
SQL

echo "Права REFERENCES выданы"
